// GENERATED CODE -- DO NOT EDIT!
// Generated by scripts\generate-protobus-setup.mjs
import * as proto from "@shared/proto/index"
import { ProtoBusClient, Callbacks } from "./grpc-client-base"

export class AccountServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.AccountService"
    static async accountLoginClicked(request: proto.caret.EmptyRequest): Promise<proto.caret.String> {
		return this.makeUnaryRequest("accountLoginClicked", request, proto.caret.EmptyRequest.toJSON, proto.caret.String.fromJSON)
	}
    static async accountLogoutClicked(request: proto.caret.EmptyRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("accountLogoutClicked", request, proto.caret.EmptyRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static subscribeToAuthStatusUpdate(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.AuthState>): ()=>void {
		return this.makeStreamingRequest("subscribeToAuthStatusUpdate", request, proto.caret.EmptyRequest.toJSON, proto.caret.AuthState.fromJSON, callbacks)
	}
    static async authStateChanged(request: proto.caret.AuthStateChangedRequest): Promise<proto.caret.AuthState> {
		return this.makeUnaryRequest("authStateChanged", request, proto.caret.AuthStateChangedRequest.toJSON, proto.caret.AuthState.fromJSON)
	}
    static async getUserCredits(request: proto.caret.EmptyRequest): Promise<proto.caret.UserCreditsData> {
		return this.makeUnaryRequest("getUserCredits", request, proto.caret.EmptyRequest.toJSON, proto.caret.UserCreditsData.fromJSON)
	}
    static async getOrganizationCredits(request: proto.caret.GetOrganizationCreditsRequest): Promise<proto.caret.OrganizationCreditsData> {
		return this.makeUnaryRequest("getOrganizationCredits", request, proto.caret.GetOrganizationCreditsRequest.toJSON, proto.caret.OrganizationCreditsData.fromJSON)
	}
    static async getUserOrganizations(request: proto.caret.EmptyRequest): Promise<proto.caret.UserOrganizationsResponse> {
		return this.makeUnaryRequest("getUserOrganizations", request, proto.caret.EmptyRequest.toJSON, proto.caret.UserOrganizationsResponse.fromJSON)
	}
    static async setUserOrganization(request: proto.caret.UserOrganizationUpdateRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("setUserOrganization", request, proto.caret.UserOrganizationUpdateRequest.toJSON, proto.caret.Empty.fromJSON)
	}
}
export class BrowserServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.BrowserService"
    static async getBrowserConnectionInfo(request: proto.caret.EmptyRequest): Promise<proto.caret.BrowserConnectionInfo> {
		return this.makeUnaryRequest("getBrowserConnectionInfo", request, proto.caret.EmptyRequest.toJSON, proto.caret.BrowserConnectionInfo.fromJSON)
	}
    static async testBrowserConnection(request: proto.caret.StringRequest): Promise<proto.caret.BrowserConnection> {
		return this.makeUnaryRequest("testBrowserConnection", request, proto.caret.StringRequest.toJSON, proto.caret.BrowserConnection.fromJSON)
	}
    static async discoverBrowser(request: proto.caret.EmptyRequest): Promise<proto.caret.BrowserConnection> {
		return this.makeUnaryRequest("discoverBrowser", request, proto.caret.EmptyRequest.toJSON, proto.caret.BrowserConnection.fromJSON)
	}
    static async getDetectedChromePath(request: proto.caret.EmptyRequest): Promise<proto.caret.ChromePath> {
		return this.makeUnaryRequest("getDetectedChromePath", request, proto.caret.EmptyRequest.toJSON, proto.caret.ChromePath.fromJSON)
	}
    static async updateBrowserSettings(request: proto.caret.UpdateBrowserSettingsRequest): Promise<proto.caret.Boolean> {
		return this.makeUnaryRequest("updateBrowserSettings", request, proto.caret.UpdateBrowserSettingsRequest.toJSON, proto.caret.Boolean.fromJSON)
	}
    static async relaunchChromeDebugMode(request: proto.caret.EmptyRequest): Promise<proto.caret.String> {
		return this.makeUnaryRequest("relaunchChromeDebugMode", request, proto.caret.EmptyRequest.toJSON, proto.caret.String.fromJSON)
	}
}
export class CheckpointsServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.CheckpointsService"
    static async checkpointDiff(request: proto.caret.Int64Request): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("checkpointDiff", request, proto.caret.Int64Request.toJSON, proto.caret.Empty.fromJSON)
	}
    static async checkpointRestore(request: proto.caret.CheckpointRestoreRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("checkpointRestore", request, proto.caret.CheckpointRestoreRequest.toJSON, proto.caret.Empty.fromJSON)
	}
}
export class FileServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.FileService"
    static async copyToClipboard(request: proto.caret.StringRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("copyToClipboard", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async openFile(request: proto.caret.StringRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("openFile", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async openImage(request: proto.caret.StringRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("openImage", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async openMention(request: proto.caret.StringRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("openMention", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async deleteRuleFile(request: proto.caret.RuleFileRequest): Promise<proto.caret.RuleFile> {
		return this.makeUnaryRequest("deleteRuleFile", request, proto.caret.RuleFileRequest.toJSON, proto.caret.RuleFile.fromJSON)
	}
    static async createRuleFile(request: proto.caret.RuleFileRequest): Promise<proto.caret.RuleFile> {
		return this.makeUnaryRequest("createRuleFile", request, proto.caret.RuleFileRequest.toJSON, proto.caret.RuleFile.fromJSON)
	}
    static async searchCommits(request: proto.caret.StringRequest): Promise<proto.caret.GitCommits> {
		return this.makeUnaryRequest("searchCommits", request, proto.caret.StringRequest.toJSON, proto.caret.GitCommits.fromJSON)
	}
    static async selectFiles(request: proto.caret.BooleanRequest): Promise<proto.caret.StringArrays> {
		return this.makeUnaryRequest("selectFiles", request, proto.caret.BooleanRequest.toJSON, proto.caret.StringArrays.fromJSON)
	}
    static async getRelativePaths(request: proto.caret.RelativePathsRequest): Promise<proto.caret.RelativePaths> {
		return this.makeUnaryRequest("getRelativePaths", request, proto.caret.RelativePathsRequest.toJSON, proto.caret.RelativePaths.fromJSON)
	}
    static async searchFiles(request: proto.caret.FileSearchRequest): Promise<proto.caret.FileSearchResults> {
		return this.makeUnaryRequest("searchFiles", request, proto.caret.FileSearchRequest.toJSON, proto.caret.FileSearchResults.fromJSON)
	}
    static async toggleClineRule(request: proto.caret.ToggleClineRuleRequest): Promise<proto.caret.ToggleClineRules> {
		return this.makeUnaryRequest("toggleClineRule", request, proto.caret.ToggleClineRuleRequest.toJSON, proto.caret.ToggleClineRules.fromJSON)
	}
    static async toggleCaretRule(request: proto.caret.ToggleCaretRuleRequest): Promise<proto.caret.ClineRulesToggles> {
		return this.makeUnaryRequest("toggleCaretRule", request, proto.caret.ToggleCaretRuleRequest.toJSON, proto.caret.ClineRulesToggles.fromJSON)
	}
    static async toggleCursorRule(request: proto.caret.ToggleCursorRuleRequest): Promise<proto.caret.ClineRulesToggles> {
		return this.makeUnaryRequest("toggleCursorRule", request, proto.caret.ToggleCursorRuleRequest.toJSON, proto.caret.ClineRulesToggles.fromJSON)
	}
    static async toggleWindsurfRule(request: proto.caret.ToggleWindsurfRuleRequest): Promise<proto.caret.ClineRulesToggles> {
		return this.makeUnaryRequest("toggleWindsurfRule", request, proto.caret.ToggleWindsurfRuleRequest.toJSON, proto.caret.ClineRulesToggles.fromJSON)
	}
    static async refreshRules(request: proto.caret.EmptyRequest): Promise<proto.caret.RefreshedRules> {
		return this.makeUnaryRequest("refreshRules", request, proto.caret.EmptyRequest.toJSON, proto.caret.RefreshedRules.fromJSON)
	}
    static async openTaskHistory(request: proto.caret.StringRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("openTaskHistory", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async toggleWorkflow(request: proto.caret.ToggleWorkflowRequest): Promise<proto.caret.ClineRulesToggles> {
		return this.makeUnaryRequest("toggleWorkflow", request, proto.caret.ToggleWorkflowRequest.toJSON, proto.caret.ClineRulesToggles.fromJSON)
	}
    static subscribeToWorkspaceUpdates(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.StringArray>): ()=>void {
		return this.makeStreamingRequest("subscribeToWorkspaceUpdates", request, proto.caret.EmptyRequest.toJSON, proto.caret.StringArray.fromJSON, callbacks)
	}
}
export class McpServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.McpService"
    static async toggleMcpServer(request: proto.caret.ToggleMcpServerRequest): Promise<proto.caret.McpServers> {
		return this.makeUnaryRequest("toggleMcpServer", request, proto.caret.ToggleMcpServerRequest.toJSON, proto.caret.McpServers.fromJSON)
	}
    static async updateMcpTimeout(request: proto.caret.UpdateMcpTimeoutRequest): Promise<proto.caret.McpServers> {
		return this.makeUnaryRequest("updateMcpTimeout", request, proto.caret.UpdateMcpTimeoutRequest.toJSON, proto.caret.McpServers.fromJSON)
	}
    static async addRemoteMcpServer(request: proto.caret.AddRemoteMcpServerRequest): Promise<proto.caret.McpServers> {
		return this.makeUnaryRequest("addRemoteMcpServer", request, proto.caret.AddRemoteMcpServerRequest.toJSON, proto.caret.McpServers.fromJSON)
	}
    static async downloadMcp(request: proto.caret.StringRequest): Promise<proto.caret.McpDownloadResponse> {
		return this.makeUnaryRequest("downloadMcp", request, proto.caret.StringRequest.toJSON, proto.caret.McpDownloadResponse.fromJSON)
	}
    static async restartMcpServer(request: proto.caret.StringRequest): Promise<proto.caret.McpServers> {
		return this.makeUnaryRequest("restartMcpServer", request, proto.caret.StringRequest.toJSON, proto.caret.McpServers.fromJSON)
	}
    static async deleteMcpServer(request: proto.caret.StringRequest): Promise<proto.caret.McpServers> {
		return this.makeUnaryRequest("deleteMcpServer", request, proto.caret.StringRequest.toJSON, proto.caret.McpServers.fromJSON)
	}
    static async toggleToolAutoApprove(request: proto.caret.ToggleToolAutoApproveRequest): Promise<proto.caret.McpServers> {
		return this.makeUnaryRequest("toggleToolAutoApprove", request, proto.caret.ToggleToolAutoApproveRequest.toJSON, proto.caret.McpServers.fromJSON)
	}
    static async refreshMcpMarketplace(request: proto.caret.EmptyRequest): Promise<proto.caret.McpMarketplaceCatalog> {
		return this.makeUnaryRequest("refreshMcpMarketplace", request, proto.caret.EmptyRequest.toJSON, proto.caret.McpMarketplaceCatalog.fromJSON)
	}
    static async openMcpSettings(request: proto.caret.EmptyRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("openMcpSettings", request, proto.caret.EmptyRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static subscribeToMcpMarketplaceCatalog(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.McpMarketplaceCatalog>): ()=>void {
		return this.makeStreamingRequest("subscribeToMcpMarketplaceCatalog", request, proto.caret.EmptyRequest.toJSON, proto.caret.McpMarketplaceCatalog.fromJSON, callbacks)
	}
    static async getLatestMcpServers(request: proto.caret.Empty): Promise<proto.caret.McpServers> {
		return this.makeUnaryRequest("getLatestMcpServers", request, proto.caret.Empty.toJSON, proto.caret.McpServers.fromJSON)
	}
    static subscribeToMcpServers(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.McpServers>): ()=>void {
		return this.makeStreamingRequest("subscribeToMcpServers", request, proto.caret.EmptyRequest.toJSON, proto.caret.McpServers.fromJSON, callbacks)
	}
}
export class ModelsServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.ModelsService"
    static async getOllamaModels(request: proto.caret.StringRequest): Promise<proto.caret.StringArray> {
		return this.makeUnaryRequest("getOllamaModels", request, proto.caret.StringRequest.toJSON, proto.caret.StringArray.fromJSON)
	}
    static async getLmStudioModels(request: proto.caret.StringRequest): Promise<proto.caret.StringArray> {
		return this.makeUnaryRequest("getLmStudioModels", request, proto.caret.StringRequest.toJSON, proto.caret.StringArray.fromJSON)
	}
    static async getVsCodeLmModels(request: proto.caret.EmptyRequest): Promise<proto.caret.VsCodeLmModelsArray> {
		return this.makeUnaryRequest("getVsCodeLmModels", request, proto.caret.EmptyRequest.toJSON, proto.caret.VsCodeLmModelsArray.fromJSON)
	}
    static async refreshOpenRouterModels(request: proto.caret.EmptyRequest): Promise<proto.caret.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshOpenRouterModels", request, proto.caret.EmptyRequest.toJSON, proto.caret.OpenRouterCompatibleModelInfo.fromJSON)
	}
    static async refreshHuggingFaceModels(request: proto.caret.EmptyRequest): Promise<proto.caret.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshHuggingFaceModels", request, proto.caret.EmptyRequest.toJSON, proto.caret.OpenRouterCompatibleModelInfo.fromJSON)
	}
    static async refreshOpenAiModels(request: proto.caret.OpenAiModelsRequest): Promise<proto.caret.StringArray> {
		return this.makeUnaryRequest("refreshOpenAiModels", request, proto.caret.OpenAiModelsRequest.toJSON, proto.caret.StringArray.fromJSON)
	}
    static async refreshRequestyModels(request: proto.caret.EmptyRequest): Promise<proto.caret.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshRequestyModels", request, proto.caret.EmptyRequest.toJSON, proto.caret.OpenRouterCompatibleModelInfo.fromJSON)
	}
    static subscribeToOpenRouterModels(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.OpenRouterCompatibleModelInfo>): ()=>void {
		return this.makeStreamingRequest("subscribeToOpenRouterModels", request, proto.caret.EmptyRequest.toJSON, proto.caret.OpenRouterCompatibleModelInfo.fromJSON, callbacks)
	}
    static async updateApiConfigurationProto(request: proto.caret.UpdateApiConfigurationRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("updateApiConfigurationProto", request, proto.caret.UpdateApiConfigurationRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async refreshGroqModels(request: proto.caret.EmptyRequest): Promise<proto.caret.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshGroqModels", request, proto.caret.EmptyRequest.toJSON, proto.caret.OpenRouterCompatibleModelInfo.fromJSON)
	}
    static async refreshBasetenModels(request: proto.caret.EmptyRequest): Promise<proto.caret.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshBasetenModels", request, proto.caret.EmptyRequest.toJSON, proto.caret.OpenRouterCompatibleModelInfo.fromJSON)
	}
}
export class SlashServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.SlashService"
    static async reportBug(request: proto.caret.StringRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("reportBug", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async condense(request: proto.caret.StringRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("condense", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON)
	}
}
export class StateServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.StateService"
    static async getLatestState(request: proto.caret.EmptyRequest): Promise<proto.caret.State> {
		return this.makeUnaryRequest("getLatestState", request, proto.caret.EmptyRequest.toJSON, proto.caret.State.fromJSON)
	}
    static async updateTerminalConnectionTimeout(request: proto.caret.UpdateTerminalConnectionTimeoutRequest): Promise<proto.caret.UpdateTerminalConnectionTimeoutResponse> {
		return this.makeUnaryRequest("updateTerminalConnectionTimeout", request, proto.caret.UpdateTerminalConnectionTimeoutRequest.toJSON, proto.caret.UpdateTerminalConnectionTimeoutResponse.fromJSON)
	}
    static async updateTerminalReuseEnabled(request: proto.caret.BooleanRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("updateTerminalReuseEnabled", request, proto.caret.BooleanRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async updateDefaultTerminalProfile(request: proto.caret.StringRequest): Promise<proto.caret.TerminalProfileUpdateResponse> {
		return this.makeUnaryRequest("updateDefaultTerminalProfile", request, proto.caret.StringRequest.toJSON, proto.caret.TerminalProfileUpdateResponse.fromJSON)
	}
    static async getAvailableTerminalProfiles(request: proto.caret.EmptyRequest): Promise<proto.caret.TerminalProfiles> {
		return this.makeUnaryRequest("getAvailableTerminalProfiles", request, proto.caret.EmptyRequest.toJSON, proto.caret.TerminalProfiles.fromJSON)
	}
    static subscribeToState(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.State>): ()=>void {
		return this.makeStreamingRequest("subscribeToState", request, proto.caret.EmptyRequest.toJSON, proto.caret.State.fromJSON, callbacks)
	}
    static async toggleFavoriteModel(request: proto.caret.StringRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("toggleFavoriteModel", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async resetState(request: proto.caret.ResetStateRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("resetState", request, proto.caret.ResetStateRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async togglePlanActModeProto(request: proto.caret.TogglePlanActModeRequest): Promise<proto.caret.Boolean> {
		return this.makeUnaryRequest("togglePlanActModeProto", request, proto.caret.TogglePlanActModeRequest.toJSON, proto.caret.Boolean.fromJSON)
	}
    static async updateAutoApprovalSettings(request: proto.caret.AutoApprovalSettingsRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("updateAutoApprovalSettings", request, proto.caret.AutoApprovalSettingsRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async updateSettings(request: proto.caret.UpdateSettingsRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("updateSettings", request, proto.caret.UpdateSettingsRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async updateTelemetrySetting(request: proto.caret.TelemetrySettingRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("updateTelemetrySetting", request, proto.caret.TelemetrySettingRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async setWelcomeViewCompleted(request: proto.caret.BooleanRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("setWelcomeViewCompleted", request, proto.caret.BooleanRequest.toJSON, proto.caret.Empty.fromJSON)
	}
}
export class TaskServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.TaskService"
    static async cancelTask(request: proto.caret.EmptyRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("cancelTask", request, proto.caret.EmptyRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async clearTask(request: proto.caret.EmptyRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("clearTask", request, proto.caret.EmptyRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async getTotalTasksSize(request: proto.caret.EmptyRequest): Promise<proto.caret.Int64> {
		return this.makeUnaryRequest("getTotalTasksSize", request, proto.caret.EmptyRequest.toJSON, proto.caret.Int64.fromJSON)
	}
    static async deleteTasksWithIds(request: proto.caret.StringArrayRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("deleteTasksWithIds", request, proto.caret.StringArrayRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async newTask(request: proto.caret.NewTaskRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("newTask", request, proto.caret.NewTaskRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async showTaskWithId(request: proto.caret.StringRequest): Promise<proto.caret.TaskResponse> {
		return this.makeUnaryRequest("showTaskWithId", request, proto.caret.StringRequest.toJSON, proto.caret.TaskResponse.fromJSON)
	}
    static async exportTaskWithId(request: proto.caret.StringRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("exportTaskWithId", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async toggleTaskFavorite(request: proto.caret.TaskFavoriteRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("toggleTaskFavorite", request, proto.caret.TaskFavoriteRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async getTaskHistory(request: proto.caret.GetTaskHistoryRequest): Promise<proto.caret.TaskHistoryArray> {
		return this.makeUnaryRequest("getTaskHistory", request, proto.caret.GetTaskHistoryRequest.toJSON, proto.caret.TaskHistoryArray.fromJSON)
	}
    static async askResponse(request: proto.caret.AskResponseRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("askResponse", request, proto.caret.AskResponseRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async taskFeedback(request: proto.caret.StringRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("taskFeedback", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async taskCompletionViewChanges(request: proto.caret.Int64Request): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("taskCompletionViewChanges", request, proto.caret.Int64Request.toJSON, proto.caret.Empty.fromJSON)
	}
    static async executeQuickWin(request: proto.caret.ExecuteQuickWinRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("executeQuickWin", request, proto.caret.ExecuteQuickWinRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static async deleteAllTaskHistory(request: proto.caret.EmptyRequest): Promise<proto.caret.DeleteAllTaskHistoryCount> {
		return this.makeUnaryRequest("deleteAllTaskHistory", request, proto.caret.EmptyRequest.toJSON, proto.caret.DeleteAllTaskHistoryCount.fromJSON)
	}
}
export class UiServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.UiService"
    static async scrollToSettings(request: proto.caret.StringRequest): Promise<proto.caret.KeyValuePair> {
		return this.makeUnaryRequest("scrollToSettings", request, proto.caret.StringRequest.toJSON, proto.caret.KeyValuePair.fromJSON)
	}
    static async onDidShowAnnouncement(request: proto.caret.EmptyRequest): Promise<proto.caret.Boolean> {
		return this.makeUnaryRequest("onDidShowAnnouncement", request, proto.caret.EmptyRequest.toJSON, proto.caret.Boolean.fromJSON)
	}
    static subscribeToAddToInput(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.String>): ()=>void {
		return this.makeStreamingRequest("subscribeToAddToInput", request, proto.caret.EmptyRequest.toJSON, proto.caret.String.fromJSON, callbacks)
	}
    static subscribeToMcpButtonClicked(request: proto.caret.WebviewProviderTypeRequest, callbacks: Callbacks<proto.caret.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToMcpButtonClicked", request, proto.caret.WebviewProviderTypeRequest.toJSON, proto.caret.Empty.fromJSON, callbacks)
	}
    static subscribeToHistoryButtonClicked(request: proto.caret.WebviewProviderTypeRequest, callbacks: Callbacks<proto.caret.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToHistoryButtonClicked", request, proto.caret.WebviewProviderTypeRequest.toJSON, proto.caret.Empty.fromJSON, callbacks)
	}
    static subscribeToChatButtonClicked(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToChatButtonClicked", request, proto.caret.EmptyRequest.toJSON, proto.caret.Empty.fromJSON, callbacks)
	}
    static subscribeToAccountButtonClicked(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToAccountButtonClicked", request, proto.caret.EmptyRequest.toJSON, proto.caret.Empty.fromJSON, callbacks)
	}
    static subscribeToSettingsButtonClicked(request: proto.caret.WebviewProviderTypeRequest, callbacks: Callbacks<proto.caret.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToSettingsButtonClicked", request, proto.caret.WebviewProviderTypeRequest.toJSON, proto.caret.Empty.fromJSON, callbacks)
	}
    static subscribeToPartialMessage(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.ClineMessage>): ()=>void {
		return this.makeStreamingRequest("subscribeToPartialMessage", request, proto.caret.EmptyRequest.toJSON, proto.caret.ClineMessage.fromJSON, callbacks)
	}
    static subscribeToTheme(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.String>): ()=>void {
		return this.makeStreamingRequest("subscribeToTheme", request, proto.caret.EmptyRequest.toJSON, proto.caret.String.fromJSON, callbacks)
	}
    static async initializeWebview(request: proto.caret.EmptyRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("initializeWebview", request, proto.caret.EmptyRequest.toJSON, proto.caret.Empty.fromJSON)
	}
    static subscribeToRelinquishControl(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToRelinquishControl", request, proto.caret.EmptyRequest.toJSON, proto.caret.Empty.fromJSON, callbacks)
	}
    static subscribeToFocusChatInput(request: proto.caret.StringRequest, callbacks: Callbacks<proto.caret.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToFocusChatInput", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON, callbacks)
	}
    static subscribeToDidBecomeVisible(request: proto.caret.EmptyRequest, callbacks: Callbacks<proto.caret.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToDidBecomeVisible", request, proto.caret.EmptyRequest.toJSON, proto.caret.Empty.fromJSON, callbacks)
	}
    static async getWebviewHtml(request: proto.caret.EmptyRequest): Promise<proto.caret.String> {
		return this.makeUnaryRequest("getWebviewHtml", request, proto.caret.EmptyRequest.toJSON, proto.caret.String.fromJSON)
	}
    static async openUrl(request: proto.caret.StringRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("openUrl", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON)
	}
}
export class WebServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.WebService"
    static async checkIsImageUrl(request: proto.caret.StringRequest): Promise<proto.caret.IsImageUrl> {
		return this.makeUnaryRequest("checkIsImageUrl", request, proto.caret.StringRequest.toJSON, proto.caret.IsImageUrl.fromJSON)
	}
    static async fetchOpenGraphData(request: proto.caret.StringRequest): Promise<proto.caret.OpenGraphData> {
		return this.makeUnaryRequest("fetchOpenGraphData", request, proto.caret.StringRequest.toJSON, proto.caret.OpenGraphData.fromJSON)
	}
    static async openInBrowser(request: proto.caret.StringRequest): Promise<proto.caret.Empty> {
		return this.makeUnaryRequest("openInBrowser", request, proto.caret.StringRequest.toJSON, proto.caret.Empty.fromJSON)
	}
}
